<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Woo.Caching</RootNamespace>
    <AssemblyName>Woo.Caching</AssemblyName>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="..\Dependencies\Woo.Dependencies.csproj" /></ItemGroup>
</Project>