<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><PackageId>Griffin.HealthCheck</PackageId><RootNamespace>Griffin.HealthCheck</RootNamespace><AssemblyName>Griffin.HealthCheck</AssemblyName></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EFCore\Griffin.EFCore.csproj" />
    <ProjectReference Include="..\EventStoreDB\Griffin.EventStoreDB.csproj" />
    <ProjectReference Include="..\Mongo\Griffin.Mongo.csproj" />
    <ProjectReference Include="..\Web\Griffin.Web.csproj" />
    <ProjectReference Include="..\Wolverine\Griffin.Wolverine.csproj" />
    <PackageReference Include="AspNetCore.HealthChecks.EventStore" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.MongoDb" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.InMemory.Storage" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="10.0.3" />
  </ItemGroup>
</Project>