name: CI

on:
  push:
    branches: [ "main"]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [ "main"]
    paths-ignore:
      - "README.md"
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Release Drafter
        if: ${{ github.ref == 'refs/heads/main' && success() }}
        id: last_release
        uses: release-drafter/release-drafter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Version Info
        run:
          echo "Release version is:" ${{ steps.last_release.outputs.tag_name }}